### ISSUE TITLE
Inception score for a different dataset

### ISSUE THREAD

**Issue by abhishekaich27** [raahii/evan#1]
How would you recommend computing the inception score for a different dataset?

**Comment by raahii** [comment]
From my understanding, there is no dataset limitation to calculate the Inception Score. Basically, you can use Inception Model trained by the UCF-101 for any dataset.

**Comment by abhishekaich27** [comment]
I tried using the Inception model trained by the UCF-101 for my custom dataset and the scores were really low. Is this expected?

**Comment by raahii** [comment]
I think it is ok if the score of each model is different and comparable... 🤔 But if the score is too low and you can't distinguish the difference from error, you should consider train the model by your own dataset from scratch.
You can use codes to train a Inception Model (3D-ResNet) from [this repository](https://github.com/kenshohara/video-classification-3d-cnn-pytorch).
