### ISSUE TITLE
Could you please provide the download link of "resnet-101-kinetics-ucf101_split1.pth"

### ISSUE THREAD

**Issue by RenYurui** [raahii/evan#3]
Thanks for your amazing repo.
I want to download the  "resnet-101-kinetics-ucf101_split1.pth" used in your code manually.
However, I cannot find the file with id="1ACPeH9prQ7yBvb2d8QsW2kt4WNgb9JId"
I use download link as "https://drive.google.com/open?id= 1ACPeH9prQ7yBvb2d8QsW2kt4WNgb9JId". 
I do not sure whether it is correct. 
Could you please provide the download link?

**Comment by raahii** [comment]
Thank you for trying using evan!

The download link is [here](https://drive.google.com/drive/folders/1zvl89AgFAApbH0At-gMuZSeQB_LpNP-M).
I borrowed trained models from [kenshohara/video-classification-3d-cnn-pytorch](https://github.com/kenshohara/video-classification-3d-cnn-pytorch).

**Comment by RenYurui** [comment]
Yes, I found this repo. 
But they did not provide "resnet-101-kinetics-ucf101_split1.pth".
They only have "resnext-101-kinetics-ucf101_split1.pth" and "resnet-101-kinetics.pth".
I download both of these weights, but they may not be incorrect.

**Comment by raahii** [comment]
Oh. I didn't know that. 
For now, please use [this](https://drive.google.com/file/d/1lP0Ec4N-ZX9U9J_PX_S4bqvOLiPw2JHK/view?usp=sharing).

I'll change code to use resnext as inception model. 
Thanks for your feedback!

**Comment by RenYurui** [comment]
Thanks for your help.
Looking forward to your update.

**Comment by liangbingzhao** [comment]
> Oh. I didn't know that. For now, please use [this](https://drive.google.com/file/d/1lP0Ec4N-ZX9U9J_PX_S4bqvOLiPw2JHK/view?usp=sharing).
> 
> I'll change code to use resnext as inception model. Thanks for your feedback!

 i can't automatically download your pth, so I need to download myself. is this link resnet or resnext?

**Comment by liangbingzhao** [comment]
i see that the link is connected to resnet, so I can just turn to your last commit and use it?
