### ISSUE TITLE
Question about IS

### ISSUE THREAD

**Issue by liangbingzhao** [raahii/evan#4]
I test your code on ucf-101 dataset, but just got 23.30108 of IS, but tgan LDVD gan infered that the IS should be about 60. wonder why

**Comment by raahii** [comment]
I don't know well about gans you mentioned, but the score depends on inception model. that's why.

**Comment by liangbingzhao** [comment]
Well, do you have c3d pretrained model(finetuned on ucf)?

**Comment by raahii** [comment]
Sorry, I don't prepare models myself. This comment may be helpful for you.
https://github.com/raahii/evan/issues/3#issuecomment-596957417
